import { Eventos } from "@/helpers/interfaces";

const eventosArray: Eventos[] = [
  {
    nombre: "Concierto A",
    categoria: "Música",
    location: "Ciudad A",
    fecha: "2023-12-01",
    stock: 200,
    precio: 40,
    comentarios: ["Increíble evento", "Gran experiencia"],
    imagen: "concierto_a.jpg",
    dueño: "Dueño A",
  },
  {
    nombre: "Vida Nocturna",
    categoria: "Vida Nocturna",
    location: "Ciudad B",
    fecha: "2023-12-05",
    stock: 150,
    precio: 25,
    comentarios: ["Partido emocionante", "Buen ambiente"],
    imagen: "deporte_b.jpg",
    dueño: "Dueño B",
  },
  {
    nombre: "Concierto C",
    categoria: "Música",
    location: "Ciudad C",
    fecha: "2023-12-10",
    stock: 300,
    precio: 50,
    comentarios: ["Diversión garantizada", "Artistas increíbles"],
    imagen: "festival_c.jpg",
    dueño: "Dueño C",
  },
  {
    nombre: "Conferencia D",
    categoria: "Artes Escenicas",
    location: "Ciudad D",
    fecha: "2023-12-15",
    stock: 100,
    precio: 15,
    comentarios: ["Interesante charla", "Buenos ponentes"],
    imagen: "conferencia_d.jpg",
    dueño: "Dueño D",
  },
  {
    nombre: "Teatro E",
    categoria: "Teatro",
    location: "Ciudad E",
    fecha: "2023-12-20",
    stock: 120,
    precio: 35,
    comentarios: ["Excelente actuación", "Historia cautivadora"],
    imagen: "teatro_e.jpg",
    dueño: "Dueño E",
  },
  {
    nombre: "Exposición F",
    categoria: "Artes Escenicas",
    location: "Ciudad F",
    fecha: "2023-12-25",
    stock: 80,
    precio: 20,
    comentarios: ["Obras impresionantes", "Ambiente cultural"],
    imagen: "exposicion_f.jpg",
    dueño: "Dueño F",
  },
  {
    nombre: "Cine G",
    categoria: "Comunidad",
    location: "Ciudad G",
    fecha: "2023-12-30",
    stock: 180,
    precio: 10,
    comentarios: ["Película emocionante", "Buena calidad"],
    imagen: "cine_g.jpg",
    dueño: "Dueño G",
  },
  {
    nombre: "Evento H",
    categoria: "Negocios",
    location: "Ciudad H",
    fecha: "2024-01-05",
    stock: 250,
    precio: 30,
    comentarios: ["Experiencia única", "Inolvidable"],
    imagen: "evento_h.jpg",
    dueño: "Dueño H",
  },
  {
    nombre: "Concierto I",
    categoria: "Música",
    location: "Ciudad I",
    fecha: "2024-01-10",
    stock: 90,
    precio: 45,
    comentarios: ["Concierto espectacular", "Risas garantizadas"],
    imagen: "show_i.jpg",
    dueño: "Dueño I",
  },
  {
    nombre: "Fiesta J",
    categoria: "Gastronomía",
    location: "Ciudad J",
    fecha: "2024-01-15",
    stock: 160,
    precio: 15,
    comentarios: ["Gran ambiente", "Música genial"],
    imagen: "fiesta_j.jpg",
    dueño: "Dueño J",
  },
  {
    nombre: "Concierto A",
    categoria: "Música",
    location: "Ciudad A",
    fecha: "2023-12-01",
    stock: 200,
    precio: 40,
    comentarios: ["Increíble evento", "Gran experiencia"],
    imagen: "concierto_a.jpg",
    dueño: "Dueño A",
  },
  {
    nombre: "Vida Nocturna",
    categoria: "Vida Nocturna",
    location: "Ciudad B",
    fecha: "2023-12-05",
    stock: 150,
    precio: 25,
    comentarios: ["Partido emocionante", "Buen ambiente"],
    imagen: "deporte_b.jpg",
    dueño: "Dueño B",
  },
  {
    nombre: "Concierto C",
    categoria: "Música",
    location: "Ciudad C",
    fecha: "2023-12-10",
    stock: 300,
    precio: 50,
    comentarios: ["Diversión garantizada", "Artistas increíbles"],
    imagen: "festival_c.jpg",
    dueño: "Dueño C",
  },
  {
    nombre: "Conferencia D",
    categoria: "Artes Escenicas",
    location: "Ciudad D",
    fecha: "2023-12-15",
    stock: 100,
    precio: 15,
    comentarios: ["Interesante charla", "Buenos ponentes"],
    imagen: "conferencia_d.jpg",
    dueño: "Dueño D",
  },
  {
    nombre: "Teatro E",
    categoria: "Teatro",
    location: "Ciudad E",
    fecha: "2023-12-20",
    stock: 120,
    precio: 35,
    comentarios: ["Excelente actuación", "Historia cautivadora"],
    imagen: "teatro_e.jpg",
    dueño: "Dueño E",
  },
  {
    nombre: "Exposición F",
    categoria: "Artes Escenicas",
    location: "Ciudad F",
    fecha: "2023-12-25",
    stock: 80,
    precio: 20,
    comentarios: ["Obras impresionantes", "Ambiente cultural"],
    imagen: "exposicion_f.jpg",
    dueño: "Dueño F",
  },
  {
    nombre: "Cine G",
    categoria: "Comunidad",
    location: "Ciudad G",
    fecha: "2023-12-30",
    stock: 180,
    precio: 10,
    comentarios: ["Película emocionante", "Buena calidad"],
    imagen: "cine_g.jpg",
    dueño: "Dueño G",
  },
  {
    nombre: "Evento H",
    categoria: "Negocios",
    location: "Ciudad H",
    fecha: "2024-01-05",
    stock: 250,
    precio: 30,
    comentarios: ["Experiencia única", "Inolvidable"],
    imagen: "evento_h.jpg",
    dueño: "Dueño H",
  },
  {
    nombre: "Concierto I",
    categoria: "Música",
    location: "Ciudad I",
    fecha: "2024-01-10",
    stock: 90,
    precio: 45,
    comentarios: ["Concierto espectacular", "Risas garantizadas"],
    imagen: "show_i.jpg",
    dueño: "Dueño I",
  },
  {
    nombre: "Fiesta J",
    categoria: "Gastronomía",
    location: "Ciudad J",
    fecha: "2024-01-15",
    stock: 160,
    precio: 15,
    comentarios: ["Gran ambiente", "Música genial"],
    imagen: "fiesta_j.jpg",
    dueño: "Dueño J",
  },
  {
    nombre: "Concierto A",
    categoria: "Música",
    location: "Ciudad A",
    fecha: "2023-12-01",
    stock: 200,
    precio: 40,
    comentarios: ["Increíble evento", "Gran experiencia"],
    imagen: "concierto_a.jpg",
    dueño: "Dueño A",
  },
  {
    nombre: "Vida Nocturna",
    categoria: "Vida Nocturna",
    location: "Ciudad B",
    fecha: "2023-12-05",
    stock: 150,
    precio: 25,
    comentarios: ["Partido emocionante", "Buen ambiente"],
    imagen: "deporte_b.jpg",
    dueño: "Dueño B",
  },
  {
    nombre: "Concierto C",
    categoria: "Música",
    location: "Ciudad C",
    fecha: "2023-12-10",
    stock: 300,
    precio: 50,
    comentarios: ["Diversión garantizada", "Artistas increíbles"],
    imagen: "festival_c.jpg",
    dueño: "Dueño C",
  },
  {
    nombre: "Conferencia D",
    categoria: "Artes Escenicas",
    location: "Ciudad D",
    fecha: "2023-12-15",
    stock: 100,
    precio: 15,
    comentarios: ["Interesante charla", "Buenos ponentes"],
    imagen: "conferencia_d.jpg",
    dueño: "Dueño D",
  },
  {
    nombre: "Teatro E",
    categoria: "Teatro",
    location: "Ciudad E",
    fecha: "2023-12-20",
    stock: 120,
    precio: 35,
    comentarios: ["Excelente actuación", "Historia cautivadora"],
    imagen: "teatro_e.jpg",
    dueño: "Dueño E",
  },
  {
    nombre: "Exposición F",
    categoria: "Artes Escenicas",
    location: "Ciudad F",
    fecha: "2023-12-25",
    stock: 80,
    precio: 20,
    comentarios: ["Obras impresionantes", "Ambiente cultural"],
    imagen: "exposicion_f.jpg",
    dueño: "Dueño F",
  },
  {
    nombre: "Cine G",
    categoria: "Comunidad",
    location: "Ciudad G",
    fecha: "2023-12-30",
    stock: 180,
    precio: 10,
    comentarios: ["Película emocionante", "Buena calidad"],
    imagen: "cine_g.jpg",
    dueño: "Dueño G",
  },
  {
    nombre: "Evento H",
    categoria: "Negocios",
    location: "Ciudad H",
    fecha: "2024-01-05",
    stock: 250,
    precio: 30,
    comentarios: ["Experiencia única", "Inolvidable"],
    imagen: "evento_h.jpg",
    dueño: "Dueño H",
  },
  {
    nombre: "Concierto I",
    categoria: "Música",
    location: "Ciudad I",
    fecha: "2024-01-10",
    stock: 90,
    precio: 45,
    comentarios: ["Concierto espectacular", "Risas garantizadas"],
    imagen: "show_i.jpg",
    dueño: "Dueño I",
  },
  {
    nombre: "Fiesta J",
    categoria: "Gastronomía",
    location: "Ciudad J",
    fecha: "2024-01-15",
    stock: 160,
    precio: 15,
    comentarios: ["Gran ambiente", "Música genial"],
    imagen: "fiesta_j.jpg",
    dueño: "Dueño J",
  },
  {
    nombre: "Concierto A",
    categoria: "Música",
    location: "Ciudad A",
    fecha: "2023-12-01",
    stock: 200,
    precio: 40,
    comentarios: ["Increíble evento", "Gran experiencia"],
    imagen: "concierto_a.jpg",
    dueño: "Dueño A",
  },
  {
    nombre: "Vida Nocturna",
    categoria: "Vida Nocturna",
    location: "Ciudad B",
    fecha: "2023-12-05",
    stock: 150,
    precio: 25,
    comentarios: ["Partido emocionante", "Buen ambiente"],
    imagen: "deporte_b.jpg",
    dueño: "Dueño B",
  },
  {
    nombre: "Concierto C",
    categoria: "Música",
    location: "Ciudad C",
    fecha: "2023-12-10",
    stock: 300,
    precio: 50,
    comentarios: ["Diversión garantizada", "Artistas increíbles"],
    imagen: "festival_c.jpg",
    dueño: "Dueño C",
  },
  {
    nombre: "Conferencia D",
    categoria: "Artes Escenicas",
    location: "Ciudad D",
    fecha: "2023-12-15",
    stock: 100,
    precio: 15,
    comentarios: ["Interesante charla", "Buenos ponentes"],
    imagen: "conferencia_d.jpg",
    dueño: "Dueño D",
  },
  {
    nombre: "Teatro E",
    categoria: "Teatro",
    location: "Ciudad E",
    fecha: "2023-12-20",
    stock: 120,
    precio: 35,
    comentarios: ["Excelente actuación", "Historia cautivadora"],
    imagen: "teatro_e.jpg",
    dueño: "Dueño E",
  },
  {
    nombre: "Exposición F",
    categoria: "Artes Escenicas",
    location: "Ciudad F",
    fecha: "2023-12-25",
    stock: 80,
    precio: 20,
    comentarios: ["Obras impresionantes", "Ambiente cultural"],
    imagen: "exposicion_f.jpg",
    dueño: "Dueño F",
  },
  {
    nombre: "Cine G",
    categoria: "Comunidad",
    location: "Ciudad G",
    fecha: "2023-12-30",
    stock: 180,
    precio: 10,
    comentarios: ["Película emocionante", "Buena calidad"],
    imagen: "cine_g.jpg",
    dueño: "Dueño G",
  },
  {
    nombre: "Evento H",
    categoria: "Negocios",
    location: "Ciudad H",
    fecha: "2024-01-05",
    stock: 250,
    precio: 30,
    comentarios: ["Experiencia única", "Inolvidable"],
    imagen: "evento_h.jpg",
    dueño: "Dueño H",
  },
  {
    nombre: "Concierto I",
    categoria: "Música",
    location: "Ciudad I",
    fecha: "2024-01-10",
    stock: 90,
    precio: 45,
    comentarios: ["Concierto espectacular", "Risas garantizadas"],
    imagen: "show_i.jpg",
    dueño: "Dueño I",
  },
  {
    nombre: "Fiesta J",
    categoria: "Gastronomía",
    location: "Ciudad J",
    fecha: "2024-01-15",
    stock: 160,
    precio: 15,
    comentarios: ["Gran ambiente", "Música genial"],
    imagen: "fiesta_j.jpg",
    dueño: "Dueño J",
  },
];

export async function generateStaticParams() {
  const categorias = [
    { nombre: "Música" },
    { nombre: "Vida nocturna" },
    { nombre: "Artes escénicas" },
    { nombre: "Gastronomía" },
    { nombre: "Negocios" },
    { nombre: "Comunidad" },
  ];
  //await fetch("https://.../posts").then((res) => res.json());

  return categorias.map((slug) => ({
    categoria: slug.nombre.toLocaleLowerCase(),
  }));
}

const Page = ({ params }: { params: { categoria: string } }) => {
  const { categoria } = params;
  console.log(categoria);

  function eliminarDiacriticosEs(texto: string) {
    return texto
      .normalize("NFD")
      .replace(
        /([^n\u0300-\u036f]|n(?!\u0303(?![\u0300-\u036f])))[\u0300-\u036f]+/gi,
        "$1"
      )
      .normalize();
  }

  const listaCategorias: any = [
    { nombre: "Música" },
    { nombre: "Vida nocturna" },
    { nombre: "Artes escénicas" },
    { nombre: "Gastronomía" },
    { nombre: "Negocios" },
    { nombre: "Comunidad" },
  ];

  const filteredEvents = eventosArray.filter((evento: Eventos) => {
    const normalizado = eliminarDiacriticosEs(evento.categoria);
    normalizado === categoria;
  });

  console.log(filteredEvents);

  return (
    <div>
      <h1 className="capitalize">Hola {categoria}</h1>
      <div>
        {eventosArray.map((evento, index) => (
          <h2 key={`${evento.nombre}${index}`}>{evento.nombre}</h2>
        ))}
      </div>
    </div>
  );
};

export default Page;
