import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { NavBar } from "@/components/NavBar";
import FooterComp from "@/components/Footer/footer";
=======
import { NavBar } from "@/components/navBar/NavBar";
>>>>>>> 90fc5b326b8b0f234913be7b09edb4b9b469a822

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eventry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={dmSans.className}>
        <NavBar />
        {children}
        <FooterComp/>
      </body>
    </html>
  );
}
