import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eventry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={dmSans.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
