import { Eventos } from "./interfaces";

export const eventosArray: Eventos[] = [
  {
    nombre: "Concierto Indie Night",
    dueño: "Indie Folks",
    categoria: "Musica",
    location: "Club TRI",
    fecha: "8 de Abril de 2024",
    stock: 2000,
    precio: 2000,
    comentarios: [],
    imagen: "/images/evento1.png",
    popular: false,
    online: false,
    id: "musica1",
  },
  {
    nombre: "Gastronomía Night",
    dueño: "Dueño 2",
    categoria: "Gastronomia",
    location: "Ubicación 2",
    fecha: "8 de Abril de 2024",
    stock: 1000,
    precio: 1500,
    comentarios: [],
    imagen: "/images/evento1.png",
    popular: false,
    online: false,
    id: "gastronomia1",
  },
  {
    nombre: "Nightlife Party",
    dueño: "Dueño 3",
    categoria: "Vida Nocturna",
    location: "Ubicación 3",
    fecha: "8 de Abril de 2024",
    stock: 800,
    precio: 0,
    comentarios: [],
    imagen: "/images/evento1.png",
    popular: false,
    online: false,
    id: "vidanocturna1",
  },
  {
    nombre: "Business Summit",
    dueño: "Dueño 4",
    categoria: "Negocios",
    location: "Ubicación 4",
    fecha: "8 de Abril de 2024",
    stock: 500,
    precio: 800,
    comentarios: [],
    imagen: "/images/evento1.png",
    popular: false,
    online: true,
    id: "negocios1",
  },
  {
    nombre: "Community Gathering",
    dueño: "Dueño 5",
    categoria: "Comunidad",
    location: "Ubicación 5",
    fecha: "8 de Abril de 2024",
    stock: 1200,
    precio: 1800,
    comentarios: [],
    imagen: "/images/evento1.png",
    popular: true,
    online: false,
    id: "comunidad1",
  },
  {
    nombre: "Community Event 2",
    dueño: "Dueño 6",
    categoria: "Comunidad",
    location: "Ubicación 6",
    fecha: "8 de Abril de 2024",
    stock: 300,
    precio: 500,
    comentarios: [],
    imagen: "/images/evento1.png",
    popular: true,
    online: true,
    id: "comunidad2",
  },
  {
    nombre: "Arts Night",
    dueño: "Dueño 7",
    categoria: "Artes Escenicas",
    location: "Ubicación 7",
    fecha: "8 de Abril de 2024",
    stock: 700,
    precio: 1000,
    comentarios: [],
    imagen: "/images/evento1.png",
    popular: false,
    online: false,
    id: "artes1",
  },
  {
    nombre: "Arts Show",
    dueño: "Dueño 8",
    categoria: "Artes Escenicas",
    location: "Ubicación 8",
    fecha: "7 de Diciembre de 2023",
    stock: 1500,
    precio: 2200,
    comentarios: [],
    imagen: "/images/evento1.png",
    popular: false,
    online: false,
    id: "artes2",
  },
  {
    nombre: "Artistic Night",
    dueño: "Dueño 9",
    categoria: "Artes Escenicas",
    location: "Ubicación 9",
    fecha: "7 de Diciembre de 2023",
    stock: 100,
    precio: 300,
    comentarios: [],
    imagen: "/images/evento1.png",
    popular: false,
    online: false,
    id: "artes3",
  },
  {
    nombre: "Music Festival",
    dueño: "Dueño 10",
    categoria: "Musica",
    location: "Ubicación 10",
    fecha: "7 de Diciembre de 2023",
    stock: 2000,
    precio: 0,
    comentarios: [],
    imagen: "/images/evento1.png",
    popular: false,
    online: true,
    id: "musica2",
  },
];
